OPENAI_API_KEY = "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"
ADMIN_PASSWORD = "clementine2024"